### ISSUE TITLE
characters

### ISSUE THREAD

**Issue by 0xAhmd** [ZachMcM/attack-on-titan-api#3]
Thank you for your work on the Attack on Titan API! It's a fantastic resource for fans and developers alike.
While using the API, I noticed that several main and important characters are currently missing. These characters play significant roles in the series and would greatly enhance the usability and completeness of the API. Here’s a list of characters that I believe should be included:
Eren Yeager
Historia Reiss
Bertolt Hoover
Ymir
Reiner Braun
Annie Leonhart
Zeke Yeager
Dot Pixis
Marco Bodt
Nile Dok
Ymir Fritz
Anka Rheinberger
Petra Rall
Grisha Yeager
Gunther Schultz
Ian Dietrich
Pieck Finger
Gabi Braun
Floch Forster
Eld Gin
Hitch Dreyse
Kitz Woermann
Carla Jaeger
Frieda Reiss
Mitabi Jarnach
Rico Brzenska
Hannes
Falco Grice
Nack Tierce
Keith Shadis

Adding these characters would make the API even more comprehensive and valuable for users who rely on it for projects and applications related to the series.
Thank you for considering this request! I look forward to seeing the API grow and evolve. Please let me know if I can provide any additional information or assistance.

**Comment by ZachMcM** [comment]
Hi, a lot of these characters are actually in the api. For these ones that aren't you can can make a pull request with the updated json file and I'll push the changes.

**Comment by 0xAhmd** [comment]
I’ll work on it soon. Appreciate the chance to contribute!
